server:
  port: 8082
  servlet:
    context-path: '/book-service/'
spring:
  application:
    name: book-api
  datasource:
      url:  jdbc:postgresql://localhost:5432/book-service
      username: postgres
      password: admin
  jpa:
    hibernate:
     ddl-auto: update
    show_sql: true
    properties:
      hibernate:
        jdbc:
          lob.non-contextual-creation: true
logging:
  level:
    com.f1rst: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO
api:
  openLibrary:
    url:
      books: 'https://openlibrary.org'
data:
  redis:
    host: ${SPRING_DATA_REDIS_HOST:localhost}
    port: ${SPRING_DATA_REDIS_PORT:6379}
