version: '3.8'

services:
  book-api:
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - redis
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"